apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookwise
resources:
  - ../../base
images:
  - name: bookwise-web
    newName: asia-southeast1-docker.pkg.dev/bookwise-509408/bookwise/bookwise-web
    newTag: local
  - name: bookwise-api
    newName: asia-southeast1-docker.pkg.dev/bookwise-509408/bookwise/bookwise-api
    newTag: local
  - name: bookwise-worker
    newName: asia-southeast1-docker.pkg.dev/bookwise-509408/bookwise/bookwise-worker
    newTag: local
  - name: bookwise-migrator
    newName: asia-southeast1-docker.pkg.dev/bookwise-509408/bookwise/bookwise-migrator
    newTag: local
