apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookwise
  namespace: bookwise
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: bookwise-ip
    networking.gke.io/managed-certificates: bookwise-certificate
    networking.gke.io/v1beta1.FrontendConfig: bookwise-frontend-config
spec:
  rules:
    - host: tai-dev-web.cloud
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: bookwise-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookwise-web
                port:
                  name: http
