apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookwise
resources:
  - namespace.yaml
  - service-accounts.yaml
  - configmap.yaml
  - web-deployment.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - services.yaml
  - migration-job.yaml
  - managed-certificate.yaml
  - frontend-config.yaml
  - ingress.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: bookwise
