apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookwise-web
  namespace: bookwise
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookwise-api
  namespace: bookwise
  annotations:
    iam.gke.io/gcp-service-account: bookwise-api@bookwise-509408.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookwise-worker
  namespace: bookwise
  annotations:
    iam.gke.io/gcp-service-account: bookwise-worker@bookwise-509408.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookwise-migrator
  namespace: bookwise
  annotations:
    iam.gke.io/gcp-service-account: bookwise-migrator@bookwise-509408.iam.gserviceaccount.com
